if has("eval")
	" Handy shortcut for name of runtimepath directory in $HOME on current
	" system (because Windows just has to be different...)
	let s:homertp = $HOME . (has("win32") ? "/vimfiles" : "/.vim")
endif

" GUI-only settings
set guioptions -=m
set guioptions -=T

" Font
if has("gui_gtk")
	" GTK does not allow fallback fonts, so we have to do some guessing
	if has("win32unix")
		" Cygwin - Use Consolas
		set guifont   =Consolas\ 10
		set linespace =1
	else
		" Other Systems - Use DejaVu Sans Mono
		set guifont =DejaVu\ Sans\ Mono\ 10
	endif
elseif has("gui_win32")
	set guifont   =Consolas:h10
	set linespace =0
	if has("directx")
		set renderoptions =type:directx,level:1,geom:1,renmode:4,taamode:0
	endif
endif

" Source local gvimrc
if filereadable(s:homertp."/local.gvimrc")
	execute 'source '.s:homertp."/local.gvimrc"
endif
