" GUI-only settings
set guioptions -=m
set guioptions -=T
set guifont     =Consolas\ 10
set linespace   =1

" Visual indicators
set listchars =tab:⇥\ ,trail:·,extends:»,precedes:«,nbsp:␣ " Use fancy Unicode characters
set showbreak =↪\ "
