execute  pathogen#infect()
filetype plugin indent on

syntax      on
set         background=dark
let         g:solarized_termcolors=256
colorscheme solarized

set cursorline
set colorcolumn=100

set tabstop=4
set shiftwidth=4
set noexpandtab

set winwidth=80
set winminwidth=20
set nowrap
