#!/bin/bash
#
# cygwin rc_config: Sets up environment rc files

# Path to rc.d dir
targetpath="$HOME/gdbash/rc.d"
# Path to dir containing source joshrc file
joshrcpath="$targetpath/cygwin"
# Path to dir containing source nanorc file (relative to ~)
nanorcpath="gdbash/rc.d/common"

# Create convenience links in home dir
ln -sTi /cygdrive/c/users/josh $HOME/josh
ln -sTi josh/google_drive $HOME/google_drive
ln -sTi google_drive/code/bash $HOME/gdbash

# Back up existing files (if they exist) to avoid losing information
if [ -f "${HOME}/.joshrc" ]; then
  mv -i $HOME/.joshrc $HOME/.joshrc_old
fi

if [ -f "${HOME}/.bash_aliases" ]; then
  mv -i $HOME/.bash_aliases $HOME/.bash_aliases_old
fi

if [ -f "${HOME}/.bash_profile" ]; then
  mv -i $HOME/.bash_profile $HOME/.bash_profile_old
fi

if [ -f "${HOME}/.bashrc" ]; then
  mv -i $HOME/.bashrc $HOME/.bashrc_old
fi

if [ -f "${HOME}/.nanorc" ]; then
  mv -i $HOME/.nanorc $HOME/.nanorc_old
fi

if [ -f "${HOME}/.startxwinrc" ]; then
  mv -i $HOME/.startxwinrc $HOME/.startxwinrc_old
fi

# Copy joshrc file to home dir
cp -i $joshrcpath/joshrc $HOME/.joshrc
# Create links to joshrc file
ln -si .joshrc $HOME/.bash_aliases
ln -si .joshrc $HOME/.bash_profile
ln -si .joshrc $HOME/.bashrc
ln -si .joshrc $HOME/.startxwinrc
# Create link to nanorc file
ln -si $nanorcpath/nanorc $HOME/.nanorc
